# permissions to do viewer sourcewatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sourcewatcher-viewer-role
rules:
- apiGroups:
  - ml.fyuan.io
  resources:
  - sourcewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.fyuan.io
  resources:
  - sourcewatchers/status
  verbs:
  - get
